export const FETCH_VOITURE_REQUEST="FETCH_VOITURE_REQUEST"
export const FETCH_VOITURE_SUCCESS="FETCH_VOITURE_SUCCESS"
export const FETCH_VOITURE_FAILURE="FETCH_VOITURE_FAILURE"

//POST voiture
export const POST_VOITURE_SUCCESS="POST_VOITURE_SECCESS"
export const POST_VOITURE_FAILURE="POST_VOITURE_FAILURE"

//delete voiture
export const DELETE_VOITURE_SUCCESS="DELETE_VOITURE_SECCESS"
export const DELETE_VOITURE_FAILURE="DELETE_VOITURE_FAILURE"

//update voiture
export const UPDATE_VOITURE_SUCCESS="UPDATE_VOITURE_SECCESS"
export const UPDATE_VOITURE_FAILURE="UPDATE_VOITURE_FAILURE"